vich_uploader:
    db_driver: orm

    mappings:
      property_image: 
        uri_prefix: /images/images1
        upload_destination: '%kernel.project_dir%/public/images/images1'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
